version: '3.8'

services:
  musicbot-prod:
    image: nekitvp/musicbot:2.1.0
    restart: on-failure
    depends_on:
      - musicbot-db
    expose:
      - "8888"
    networks:
      - musicbot-prod
    environment:
      DB_HOST: musicbot-db
      DB_PORT: 5432
      DB_NAME: musicBot
      DB_USERNAME: postgres
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      SPRING_PROFILES_ACTIVE: prod

  musicbot-db:
    container_name: musicbot-db
    image: postgres:12-alpine
    restart: on-failure
    volumes:
      - /pgdata-musicbot/var/lib/postgresql/data
    expose:
      - "5432"
    ports:
      - "9736:5432"
    networks:
      - musicbot-prod
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: musicBot

networks:
  musicbot-prod:

volumes:
  pgdata-musicbot:
