version: '3.8'

services:
  musicbot-dev:
    image: nekitvp/musicbot:1.0.0
    restart: on-failure
    depends_on:
      - musicbot-db
    expose:
      - "8080"
    ports:
      - "5006:8080"
    networks:
      - musicbot-dev
    environment:
      DB_HOST: musicbot-db
      DB_PORT: 5432
      DB_USERNAME: postgres
      DB_PASSWORD: ks51zcVavcChfepPaeORY5aGff9904fU
      SPRING_PROFILES_ACTIVE: develop
      DB_NAME: musicbot

  musicbot-db:
    container_name: musicbot-db
    image: postgres:12-alpine
    restart: on-failure
    volumes:
      - pgdata-musicbot-dev:/var/lib/postgresql/data
    expose:
      - "5432"
    ports:
      - "2345:5432"
    networks:
      - musicbot-dev
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ks51zcVavcChfepPaeORY5aGff9904fU
      POSTGRES_DB: musicbot

networks:
  musicbot-dev:

volumes:
  pgdata-musicbot-dev:
